### ISSUE TITLE
Incorrect invalid value detection when using a negative n value in :nth-* selectors

### ISSUE THREAD

**Issue by teddybradford** [jonnyhaynes/language-SCSS#3]
Syntax is incorrectly parsed as an invalid value when using a negative n value in :nth-* selectors (e.g., `:nth-child(-n+9)`).

![](http://i.imgur.com/xP3Xx2f.png)

```scss
&:not(:nth-last-child(-n + #{$cycle})) {
    margin-bottom: $gutter;
  }
```
